import axios from 'axios';
import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';

const Home = (props) => {
  const { data } = props;
  const [dataFiltered, setDataFiltered] = useState(data);

  /**
   * Search Surah
   *
   * @param {React.ChangeEvent<HTMLInputElement>} e
   */
  const onSearch = (e) => {
    const { value: search } = e.target;

    setDataFiltered(() => {
      const newData = data.filter((value, index) => {
        const regex = new RegExp(`${search}`, 'i');
        return regex.test(value.nama_latin)
          ? true
          : regex.test(value.arti)
          ? true
          : false;
      });

      return newData;
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-8">
        <h1 className="text-center text-4xl font-bold">
          Welcome to <span className="text-blue-500">Qur'an</span>
        </h1>

        <div className="flex justify-center my-4">
          <input
            type="text"
            className="border-2 border-slate-300 rounded-l-lg focus:outline-blue-300 px-2 py-1"
            placeholder="Search..."
            onChange={onSearch}
          />
          <button className="bg-blue-500 text-white rounded-r-md py-2 px-3">
            Search
          </button>
        </div>

        <section className="lg:w-4/5 py-4 mx-auto">
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
            {dataFiltered?.map((value, index) => {
              return (
                <Link key={index} href={`/surah/${value.nomor}`}>
                  <a className="relative text-center border border-slate-400 rounded-2xl p-4">
                    <span
                      className={`absolute flex -top-2 -left-2 bg-red-500 text-white text-sm justify-center items-center font-bold rounded-full h-8 w-8`}
                    >
                      {value.nomor}
                    </span>
                    <p className="text-xl">{value.nama}</p>
                    <h2 className="text-blue-500 font-bold text-lg">
                      {value.nama_latin}
                    </h2>
                    <p className="font-thin">{value.arti}</p>
                    <p className="text-red-500">({value.jumlah_ayat}) ayat</p>
                  </a>
                </Link>
              );
            })}
          </div>
        </section>
      </main>
    </>
  );
};

export const getServerSideProps = async () => {
  const response = await axios.get('https://equran.id/api/surat', {
    responseType: 'json',
  });

  return {
    props: { data: response.data },
  };
};

export default Home;
